### ISSUE TITLE
'TqdmToLogger' object has no attribute '_logging_on_close'

### ISSUE THREAD

**Issue by 2020namemyself2020** [visinf/self-mono-sf#21]
Hello, Sorry to interrupt you. I am interested in your work. But I meet a problem when I run 'train_monosf_selfsup_kitti_raw.sh'. 
----------------------------------------------------------------
Traceback (most recent call last):
  File "../main.py", line 90, in <module>
    main()
  File "../main.py", line 87, in main
    validation_augmentation=validation_augmentation)
  File "/data/self-mono-sf-master/core/runtime.py", line 455, in exec_runtime
    total_progress = create_progressbar(**progressbar_args)
  File "/data/self-mono-sf-master/core/runtime.py", line 92, in create_progressbar
    return tools.tqdm_with_logging(**tqdm_args)
  File "/data/self-mono-sf-master/core/tools.py", line 398, in tqdm_with_logging
    logging_on_update=logging_on_update)
  File "/data/self-mono-sf-master/core/tools.py", line 344, in __init__
    postfix=postfix)
  File "/data/my_anaconda3/envs/self_mono/lib/python3.7/site-packages/tqdm/std.py", line 1109, in __init__
    self.refresh(lock_args=self.lock_args)
  File "/data/my_anaconda3/envs/self_mono/lib/python3.7/site-packages/tqdm/std.py", line 1361, in refresh
    self.display()
  File "/data/my_anaconda3/envs/self_mono/lib/python3.7/site-packages/tqdm/std.py", line 1509, in display
    self.sp(self.__str__() if msg is None else msg)
  File "/data/my_anaconda3/envs/self_mono/lib/python3.7/site-packages/tqdm/std.py", line 1165, in __str__
    return self.format_meter(**self.format_dict)
TypeError: format_meter() got an unexpected keyword argument 'nrows'
Exception ignored in: <function tqdm.__del__ at 0x7f2c0ed42f80>
Traceback (most recent call last):
  File "/data/my_anaconda3/envs/self_mono/lib/python3.7/site-packages/tqdm/std.py", line 1162, in __del__
    self.close()
  File "/data/self-mono-sf-master/core/tools.py", line 374, in close
    if self._logging_on_close and not self._closed:
AttributeError: 'TqdmToLogger' object has no attribute '_logging_on_close'

**Comment by hurjunhwa** [comment]
Hi,

It would be better to use an older version of Tqdm.
Please refer to this [issue](https://github.com/visinf/self-mono-sf/issues/5).

**Comment by 2020namemyself2020** [comment]
Thanks, It really works!
Thank you sincerely
